<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../../BaseUnit.php';
/**
 * Test class for ApplicationException.
 * Generated by gentests.php on 2013-07-20 at 17:17:15.
 */
class ApplicationExceptionTest extends BaseUnit
{
    /**
     * @var \s3c3\except\ApplicationException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\except\ApplicationException();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


// ----- added by gentests.php on 2013-07-20 at 17:17:15 -----


    /**
     * Test function for getSeverity()
     */
    public function testGetSeverity()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for getSeverityName()
     */
    public function testGetSeverityName()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
