<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../../BaseUnit.php';
/**
 * Test class for ConfigurationException.
 * Generated by gentests.php on 2013-07-20 at 17:17:15.
 */
class ConfigurationExceptionTest extends BaseUnit
{
    /**
     * @var \s3c3\except\ConfigurationException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\except\ConfigurationException();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}