<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../../BaseUnit.php';
/**
 * Test class for SchemeNameException.
 * Generated by gentests.php on 2013-07-21 at 16:23:25.
 */
class SchemeNameExceptionTest extends BaseUnit
{
    /**
     * @var \s3c3\except\SchemeNameException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\except\SchemeNameException();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}