<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../BaseUnit.php';
/**
 * Test class for .
 * Generated by gentests.php on 2013-07-12 at 12:01:03.
 */
class BootstrapTest extends BaseUnit
{
    /**
     * @var \\
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \\();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


// ----- added by gentests.php on 2013-07-20 at 17:21:11 -----


    /**
     * Test function for run()
     */
    public function testRun()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
