<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../BaseUnit.php';
/**
 * Test class for CertHandler.
 * Generated by gentests.php on 2013-07-20 at 17:21:11.
 */
class CertHandlerTest extends BaseUnit
{
    /**
     * @var \s3c3\bootstrap\CertHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\bootstrap\CertHandler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


// ----- added by gentests.php on 2013-07-20 at 17:21:11 -----


    /**
     * Test function for loadCertificate($name, $purpose, $certstring)
     */
    public function testLoadCertificate()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for writeToStore()
     */
    public function testWriteToStore()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for applyCRL($crl)
     */
    public function testApplyCRL()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
