<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../../../BaseUnit.php';
/**
 * Test class for ConfigItem.
 * Generated by gentests.php on 2013-07-20 at 17:17:15.
 */
class ConfigItemTest extends BaseUnit
{
    /**
     * @var \s3c3\core\model\ConfigItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\core\model\ConfigItem();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


// ----- added by gentests.php on 2013-07-20 at 17:17:15 -----


    /**
     * Test function for writeConfigItem($key, $value, $create = false)
     */
    public function testWriteConfigItem()
    {                                                             
        $this->assertTrue(
            \s3c3\core\model\ConfigItem::writeConfigItem('unittest','test', true));
        $this->assertTrue(
            \s3c3\core\model\ConfigItem::writeConfigItem('token.expire',5));
    }

    /**
     * Test function for readConfigItems($writeConfig = false)
     */
    public function testReadConfigItems()
    {
        $retarr = \s3c3\core\model\ConfigItem::readConfigItems(true);
        $this->assertEquals($retarr['unittest'], 'test');
    }

}
