<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../BaseUnit.php';
/**
 * Test class for ClassLoader.
 * Generated by gentests.php on 2013-07-12 at 12:03:26.
 */
class ClassLoaderTest extends BaseUnit
{
    /**
     * @var \s3c3\ClassLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\ClassLoader();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


// ----- added by gentests.php on 2013-07-12 at 12:03:26 -----


    /**
     * Test function for addNamespace($namespace, $path = '.',
		$namespaceSeparator = '\\', $extension = '.php')
     */
    public function testAddNamespace()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for addDefaultNamespace()
     */
    public function testAddDefaultNamespace()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for register()
     */
    public function testRegister()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for unregister()
     */
    public function testUnregister()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for loadClass($classname)
     */
    public function testLoadClass()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }


}
