<?php
namespace s3c3\unittest;
require_once __DIR__ . '/../BaseUnit.php';
/**
 * Test class for ErrorHandler.
 * Generated by gentests.php on 2013-07-20 at 17:17:15.
 */
class ErrorHandlerTest extends BaseUnit
{
    /**
     * @var \s3c3\ErrorHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // uncomment the following line to set an object to this object
        //$this->object = new \s3c3\ErrorHandler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


// ----- added by gentests.php on 2013-07-20 at 17:17:15 -----


    /**
     * Test function for handleException(\Exception $e)
     */
    public function testHandleException()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test function for handleError($errno, $errstr, $errfile, $errline)
     */
    public function testHandleError()
    {
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
